# ----------------------------------------------------------------------
# LoRA FINE-TUNING SCRIPT (Qwen 2.5 – NL → XML SFT)
# ----------------------------------------------------------------------
# Purpose: # Fine-tunes a Qwen2.5 Instruct model using LoRA on a
#            supervised dataset where the task is: Natural Language AMI scenario → Structured <Gen> XML
#            Expected Inputs:
#              - Pre-tokenized .pt datasets generated by 02-build-sft-*.py
#              - Each sample already contains:
#                    input_ids
#                    attention_mask
#                    labels (with prompt masked as -100)
#
#           Pipeline Position:
#             1) Build dataset (02-build-sft-*.py)
#             2) Validate dataset (03-check_dataset_xml.py)
#             3) Run this script to train LoRA adapter
#             4) Run inference sanity check / AB tests
#
#           What we do :
#             - Loads base Qwen model (fp16, single GPU)
#             - Injects LoRA adapters into attention projection layers
#             - Trains only LoRA parameters (base model frozen)
#             - Uses dynamic padding collator
#             - Runs step-based evaluation
#             - Saves final adapter to: adapter_final/
#
#          Notes:
#           - Gradient checkpointing enabled for memory efficiency
#           - remove_unused_columns=False required for custom dataset
#           - label_names=["labels"] required for PEFT compatibility
#           - Learning rate default (1e-4) tuned for LoRA
#
# Example :
#          python 04-train-qwen-lora.py \  
#              --model Qwen/Qwen2.5-3B-Instruct  \
#              --train-pt out\sft_min_4k\train_4k_tokenized.pt  \
#              --val-pt out\sft_min_4k\val_4k_tokenized.pt  \
#              --out-dir outputs\qwen2p5_3b_sft_min_4k_lora \
#              --max-steps 140  --lr 1e-4  --grad-accum 16  --warmup-ratio 0.03 \
#              --logging-steps 10  --eval-steps 100  --save-steps 200  \
#              --attn-impl sdpa  --gpu 0  --trust-remote-c 
# ----------------------------------------------------------------------

import os
import math
import argparse
from dataclasses import dataclass
from typing import List, Dict

import torch
from torch.utils.data import Dataset

from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments
from peft import LoraConfig, get_peft_model, TaskType





def mem(tag=""):
    a = torch.cuda.memory_allocated() / 1024**3
    r = torch.cuda.memory_reserved() / 1024**3
    f, t = torch.cuda.mem_get_info()
    print(f"[MEM {tag}] alloc={a:.2f}GB reserved={r:.2f}GB free={f/1024**3:.2f}GB total={t/1024**3:.2f}GB")



# -----------------------
# Dataset (from .pt cache)
# -----------------------
class TokenizedPTDataset(Dataset):
    def __init__(self, pt_path: str):
        self.data = torch.load(pt_path, weights_only=False)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        ex = self.data[idx]
        return {
            "input_ids": ex["input_ids"],
            "attention_mask": ex["attention_mask"],
            "labels": ex["labels"],
        }


# -----------------------
# Collator: dynamic padding
# -----------------------
@dataclass
class DataCollatorForCausalLMWithLabels:
    pad_token_id: int
    label_pad_id: int = -100

    def __call__(self, features: List[Dict[str, torch.Tensor]]) -> Dict[str, torch.Tensor]:
        max_len = max(f["input_ids"].numel() for f in features)

        def pad_1d(x, pad_value):
            if x.numel() == max_len:
                return x
            pad = torch.full((max_len - x.numel(),), pad_value, dtype=x.dtype)
            return torch.cat([x, pad], dim=0)

        input_ids = torch.stack([pad_1d(f["input_ids"], self.pad_token_id) for f in features])
        attention_mask = torch.stack([pad_1d(f["attention_mask"], 0) for f in features])
        labels = torch.stack([pad_1d(f["labels"], self.label_pad_id) for f in features])

        return {"input_ids": input_ids, "attention_mask": attention_mask, "labels": labels}


def main():
    ap = argparse.ArgumentParser()
    ## ap.add_argument("--model", default="Qwen/Qwen2.5-7B-Instruct")
    ap.add_argument("--model", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--train-pt", default=os.path.join("out", "sft_min_8k", "train_8k_tokenized.pt"))
    ap.add_argument("--val-pt", default=os.path.join("out", "sft_min_8k", "val_8k_tokenized.pt"))
    ap.add_argument("--out-dir", default=os.path.join("outputs", "qwen2p5_sft_min_8k_lora"))
    ## ap.add_argument("--max-steps", type=int, default=30)
    ap.add_argument("--max-steps", type=int, default=800)   # start here    
    ## ap.add_argument("--lr", type=float, default=2e-5)
    ap.add_argument("--lr", type=float, default=1e-4)       # LoRA likes higher LR
    ap.add_argument("--batch", type=int, default=1)
    ap.add_argument("--grad-accum", type=int, default=16)
    ap.add_argument("--warmup-ratio", type=float, default=0.03)
    ap.add_argument("--logging-steps", type=int, default=5)
    ap.add_argument("--eval-steps", type=int, default=15)
    ap.add_argument("--save-steps", type=int, default=15)
    ap.add_argument("--seed", type=int, default=1337)
    ap.add_argument("--trust-remote-code", action="store_true")
    ap.add_argument("--attn-impl", default="sdpa", choices=["eager", "sdpa"])
    ap.add_argument("--gpu", type=int, default=0)  # force single GPU
    args = ap.parse_args()

    os.makedirs(args.out_dir, exist_ok=True)

    # Force single GPU (important on Windows to avoid DataParallel surprises)
    torch.cuda.set_device(args.gpu)
    device = torch.device("cuda")

    print("[INFO] Loading tokenizer...")
    tok = AutoTokenizer.from_pretrained(args.model, use_fast=True, trust_remote_code=args.trust_remote_code)
    if tok.pad_token is None and tok.eos_token is not None:
        tok.pad_token = tok.eos_token

    print("[INFO] Memory after loading tokenizer...")
    mem("after_load")

    print("[INFO] Loading model on ONE GPU (no device_map)...")
    model = AutoModelForCausalLM.from_pretrained(
        args.model,
        torch_dtype=torch.float16,
        trust_remote_code=args.trust_remote_code,
        attn_implementation=args.attn_impl,
    ).to(device)

    model.config.use_cache = False

    print("[INFO] Memory after Loading model on ONE GPU ...")
    mem("after_load")

    # LoRA
    lora = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=8,
        lora_alpha=16,
        lora_dropout=0.05,
        bias="none",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )
    model.enable_input_require_grads()
    model = get_peft_model(model, lora)

    # Trainable params float32 for stability
    for p in model.parameters():
        if p.requires_grad:
            p.data = p.data.float()

    model.print_trainable_parameters()

    train_ds = TokenizedPTDataset(args.train_pt)
    val_ds = TokenizedPTDataset(args.val_pt)
    collator = DataCollatorForCausalLMWithLabels(pad_token_id=tok.pad_token_id)

    steps_per_epoch = math.ceil(len(train_ds) / (args.batch * args.grad_accum))
    print(f"[INFO] Train examples: {len(train_ds)} | Val: {len(val_ds)}")
    print(f"[INFO] Approx steps/epoch (batch={args.batch}, accum={args.grad_accum}): {steps_per_epoch}")

    targs = TrainingArguments(
        output_dir=args.out_dir,
        seed=args.seed,
        per_device_train_batch_size=args.batch,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        warmup_ratio=args.warmup_ratio,
        max_steps=args.max_steps,
        fp16=True,
        optim="adamw_torch",
        logging_steps=args.logging_steps,
        eval_strategy="steps",
        eval_steps=args.eval_steps,
        save_strategy="steps",
        save_steps=args.save_steps,
        save_total_limit=2,
        gradient_checkpointing=True,
        report_to="none",
        remove_unused_columns=False,   # IMPORTANT for custom batches
        label_names=["labels"],        # IMPORTANT for PEFT/Trainer
    )

    trainer = Trainer(
        model=model,
        args=targs,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=collator,
        tokenizer=tok,
    )

    print("[INFO] Memory Before Starting Training ...")
    mem("after_load")

    print("[INFO] Starting training...")
    trainer.train()

    print("[INFO] Memory After Starting Training ...")
    mem("after_load")    

    print("[INFO] Saving final adapter...")
    trainer.model.save_pretrained(os.path.join(args.out_dir, "adapter_final"))
    tok.save_pretrained(os.path.join(args.out_dir, "adapter_final"))
    print("[DONE] Training complete.")


if __name__ == "__main__":
    main()
